# Generated by Django 4.0.3 on 2022-03-16 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='user',
            field=models.OneToOneField(default=1,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL), preserve_default=False,
        ),
    ]
