# Generated by Django 4.0.3 on 2022-03-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0002_remove_personalprofile_user_id_personalprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
