# Generated by Django 4.0.3 on 2022-03-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0003_personalprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
