# Generated by Django 4.0.3 on 2022-03-28 18:31

from django.db import migrations


def saving_profiles(apps, schema_editor):
    PersonalProfile = apps.get_model('personal_profile', 'PersonalProfile')
    for profile in PersonalProfile.objects.all():
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0005_personalprofile_resume'),
    ]

    operations = [
        migrations.RunPython(saving_profiles),
    ]
