# Generated by Django 4.0.3 on 2022-03-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0006_auto_20220328_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
