# Generated by Django 4.0.3 on 2022-04-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0008_alter_personalprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
