JOB_TYPES = [
    ('Delivery driver'),
    ('Web developer'),
    ('Lecturer'),
    ('Secretary'),
    ('Customer service'),
    ('Human resources'),
    ('Sales Manager'),
    ('Waiter'),
    ('Teacher'),
    ('Accountant'),
    ('Statistician'),
    ('Electrician'),
    ('Architect'),
    ('Database Administrator'),
    ('Art Director'),
    ('Graphic Designer'),
    ('Photographer'),
    ('Editor'),
    ('Librarian'),
]
