# Generated by Django 4.0.3 on 2022-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_test_data_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='work_schedule',
            field=models.CharField(
                choices=[
                    ('Not specified', 'Not specified'), ('Full-time', 'Full-time'),
                    ('Part-time', 'Part-time'), ('Flexible', 'Flexible')],
                default='Not specified', max_length=30),
        ),
        migrations.AlterField(
            model_name='preference',
            name='years_of_experience',
            field=models.CharField(
                choices=[
                    ('no experience', 'no experience'), ('0-2 years', '0-2 years'),
                    ('3-5 years', '3-5 years'), ('5+ years', '5+ years')],
                default='no experience', max_length=30),
        ),
        migrations.DeleteModel(
            name='YearsOfExperience',
        ),
    ]
