# Generated by Django 4.0.3 on 2022-04-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_preference_work_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='job_board.jobtype'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='job_board.location'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='work_schedule',
            field=models.CharField(
                choices=[
                    ('Not specified', 'Notspecified'), ('Full-time', 'Fulltime'),
                    ('Part-time', 'Parttime'), ('Flexible', 'Flexible')],
                default='Not specified', max_length=30),
        ),
        migrations.AlterField(
            model_name='preference',
            name='years_of_experience',
            field=models.CharField(
                choices=[
                    ('Not specified', 'Notspecified'), ('no experience', 'Noexperience'),
                    ('0-2 years', 'Years0To2'), ('3-5 years', 'Years3To5'), ('5+ years', 'Years5Andabove')],
                default='Not specified', max_length=30),
        ),
    ]
