# Generated by Django 4.0.3 on 2022-04-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_alter_preference_job_type_alter_preference_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='work_schedule',
            field=models.CharField(
                choices=[
                    ('Not specified', 'Not specified'), ('Full-time', 'Full-time'),
                    ('Part-time', 'Part-time'), ('Flexible', 'Flexible')],
                default='Not specified', max_length=30),
        ),
        migrations.AlterField(
            model_name='preference',
            name='years_of_experience',
            field=models.CharField(
                choices=[
                    ('Not specified', 'Not specified'), ('No experience', 'No experience'), ('0-2 years', '0-2 years'),
                    ('3-5 years', '3-5 years'), ('5+ years', '5+ years')],
                default='Not specified', max_length=30),
        ),
    ]
