# Generated by Django 4.0.3 on 2022-03-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_comment_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_parent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='comments',
                to='feed.post'),
        ),
    ]
