# Generated by Django 4.0.3 on 2022-03-28 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_test_data_years_of_experiences'),
        ('feed', '0006_post_likes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='prefernces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='job_board.preference'),
        ),
    ]
