POSTS = [
    [
        'Microsoft Is Hiring!',
        'We are looking for a delivry driver to work at our Haifa office',
        'Bill Gates',
        True,
        'Delivery driver',
    ],
    [
        'Apple Is Hiring!',
        'We are looking for a web developer to work at our Tel Aviv office',
        'Tim Cook',
        True,
        'Web developer',
    ],
    [
        'Microsoft Is Hiring!',
        'We are looking for a graphic designer to work at our Herzelia offices',
        'Bill Gates',
        True,
        'Graphic Designer',
    ],
    [
        'Apple Is Hiring!',
        'We are looking for a database administrator to work at our Tel Aviv office',
        'Tim Cook',
        True,
        'Database Administrator',
    ],
    [
        'Microsoft Is Hiring!',
        'We are looking for an accountant to work at our Tel Aviv office',
        'Bill Gates',
        True,
        'Accountant',
    ],
    [
        'Apple Is Hiring!',
        'We are looking for a talented human resources specialist to work at our Tel Aviv office',
        'Tim Cook',
        True,
        'Human resources',
    ],
    [
        'Im a Job Seeker!',
        'Looking for a delivery driver opportunity',
        'John Doe',
        False,
        None,
    ],
    [
        'Im Job Seeking!',
        'Looking for a django web developing opportunity',
        'Jane Doe',
        False,
        None,
    ],
    [
        'Im a Job Seeker!',
        'Looking for a secretary full time position',
        'Jane Doe',
        False,
        None,
    ],
    [
        'I am looking for a job!',
        'Looking for an electrician position',
        'John Doe',
        False,
        None,
    ],
    [
        'Please help me find a job',
        'Looking for a Graphic Designer opportunity',
        'Jane Doe',
        False,
        None,
    ],
    [
        'Im Job Seeking!',
        'Looking for a librarian opportunity',
        'John Doe',
        False,
        None,
    ],
]
